In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA, NMF
from sklearn.preprocessing import Normalizer, StandardScaler

In [32]:
books = pd.read_csv("BooksDatasetClean.csv")
books = books.dropna()
books.head()

Title  \
7                          Journey Through Heartsongs   
8                        In Search of Melancholy Baby   
10       The Dieter's Guide to Weight Loss During Sex   
11  Germs : Biological Weapons and America's Secre...   
13  The Good Book: Reading the Bible with Mind and...   

                                              Authors  \
7                           By Stepanek, Mattie J. T.   
8   By Aksyonov, Vassily, Heim, Michael Henry, and...   
10                                  By Smith, Richard   
11  By Miller, Judith, Engelberg, Stephen, and Bro...   
13                                 By Gomes, Peter J.   

                                          Description  \
7   Collects poems written by the eleven-year-old ...   
8   The Russian author offers an affectionate chro...   
10  A humor classic, this tongue-in-cheek diet pla...   
11  Deadly germs sprayed in shopping malls, bomb-l...   
13  "The Bible and the social and moral consequenc...   

                                        Category                   Publisher  \
7                               Poetry , General                   VSP Books   
8            Biography & Autobiography , General                Random House   
10   Health & Fitness , Diet & Nutrition , Diets  Workman Publishing Company   
11   Technology & Engineering , Military Science            Simon & Schuster   
13       Religion , Biblical Biography , General            Harper Perennial   

    Price Starting With ($) Publish Date (Month)  Publish Date (Year)  
7                     19.96            September                 2001  
8                      4.99                 June                 1987  
10                     4.99              January                 1978  
11                     4.99              October                 2001  
13                     5.29                  May                 1998

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

features = books['Description'] + books['Category']
tfidf = TfidfVectorizer(token_pattern=r'(?u)\b[^\d\W]+\b')
csr_matrix = tfidf.fit_transform(features)
words = tfidf.get_feature_names_out()
print(words)

['_' '___' '____' ... 'flavorful' 'flavors' 'flees']


In [39]:
print(csr_matrix)

  (0, 19308)	0.25790244139150287
  (0, 76321)	0.2186393773631332
  (0, 111863)	0.15027717687269057
  (0, 13955)	0.07692340992527777
  (0, 100330)	0.08322459363821798
  (0, 30941)	0.2327995665183381
  (0, 112286)	0.13170446863210317
  (0, 70238)	0.12767952458087267
  (0, 66371)	0.31472606579509305
  (0, 29879)	0.3639784167498535
  (0, 73304)	0.236224444135786
  (0, 90231)	0.21988918281607003
  (0, 45556)	0.2480976210541988
  (0, 35105)	0.20407462242515875
  (0, 3266)	0.08039856312867293
  (0, 101088)	0.21809686604096534
  (0, 253)	0.09817068289512873
  (0, 57037)	0.08886921750749315
  (0, 24622)	0.23788974843856084
  (0, 69844)	0.043373277437482205
  (0, 91181)	0.23721482262811144
  (0, 67143)	0.16653523726808128
  (0, 34336)	0.17474002023506574
  (0, 46316)	0.16976142285057225
  (0, 76335)	0.2120137168802623
  :	:
  (65294, 48179)	0.16040118591644825
  (65294, 97210)	0.15835129720087127
  (65294, 81403)	0.1673770470172482
  (65294, 78804)	0.13723166067135936
  (65294, 47609)	0.16847362

In [41]:
model = NMF(n_components=6)
model.fit(csr_matrix)
features = model.transform(csr_matrix)
print(features)

[[0.00747029 0.         0.         0.00148659 0.02847318 0.00017155]
 [0.037129   0.         0.         0.00090612 0.         0.00232815]
 [0.01486267 0.         0.02099396 0.01566584 0.00029396 0.010319  ]
 ...
 [0.01924635 0.00212058 0.00956242 0.02483403 0.00999203 0.        ]
 [0.01774119 0.         0.         0.02627951 0.         0.00300921]
 [0.00600839 0.         0.         0.02428192 0.         0.        ]]
